services:
  _defaults:
    autowire: true
    autoconfigure: true

  Txt\:
    resource: '../../src/Txt/'
    exclude:
      - '../../src/Txt/Domain/Model/'
      - '../../src/Kernel.php'
      - '../../src/Tests/'


  Txt\Infrastructure\Controller\:
    resource: '../../src/Txt/Infrastructure/Controller/'
    tags: [ 'controller.service_arguments' ]


  Txt\Infrastructure\Listener\JsonTransformerExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }