txt_health_check:
    path: /txt/health-check
    controller: Txt\Infrastructure\Controller\HealthCheckController
    methods: [ GET ]

create_txt:
    path: /txt/create
    controller: Txt\Infrastructure\Controller\Txt\CreateTxtController
    methods: [ POST ]

search_txts:
    path: /txt/search
    controller: Txt\Infrastructure\Controller\Txt\SearchTxtController
    methods: [ GET ]

get_txt_by_id:
    path: /txt/{id}
    controller: Txt\Infrastructure\Controller\Txt\GetTxtByIdController
    methods: [ GET ]

delete_txt:
    path: /txt/{id}
    controller: Txt\Infrastructure\Controller\Txt\DeleteTxtController
    methods: [ DELETE ]

update_txt:
    path: /txt/{id}
    controller: Txt\Infrastructure\Controller\Txt\UpdateTxtController
    methods: [ PATCH ]

type_health_check:
    path: /type/health-check
    controller: Type\Infrastructure\Controller\HealthCheckController
    methods: [ GET ]

create_type:
    path: /type/create
    controller: Type\Infrastructure\Controller\Type\CreateTypeController
    methods: [ POST ]

search_types:
    path: /type/search
    controller: Type\Infrastructure\Controller\Type\SearchTypeController
    methods: [ GET ]

get_type_by_id:
    path: /type/{id}
    controller: Type\Infrastructure\Controller\Type\GetTypeByIdController
    methods: [ GET ]

delete_type:
    path: /type/{id}
    controller: Type\Infrastructure\Controller\Type\DeleteTypeController
    methods: [ DELETE ]

update_type:
    path: /type/{id}
    controller: Type\Infrastructure\Controller\Type\UpdateTypeController
    methods: [ PATCH ]