txt_health_check:
    path: /txt/health-check
    controller: Txt\Infrastructure\Controller\HealthCheckController
    methods: [ GET ]

create_txt:
    path: /txt/create
    controller: Txt\Infrastructure\Controller\Txt\CreateTxtController
    methods: [ POST ]

get_txt_by_id:
    path: /txt/{id}
    controller: Txt\Infrastructure\Controller\Txt\GetTxtByIdController
    methods: [ GET ]