doctrine:
    orm:
        mappings:
            Txt:
                type: xml
                dir: "%kernel.project_dir%/src/Txt/Infrastructure/Database/ORM/Doctrine/mapping"
                prefix: Txt\Domain\Model
                is_bundle: false
framework:
    serializer:
        mapping:
            paths: ['%kernel.project_dir%/src/Txt/Infrastructure/Database/ORM/serializer-native']
